#!/bin/bash -ex

OCROOT=/var/www/opencart
CONFIG_FILE=$OCROOT/config.php
ADMINCONFIG_FILE=$OCROOT/admin/config.php
NAME=oc2
DB_PREFIX=oc_
DB_PASSWORD=$(mcookie)


# increase php running limits
PHPINI=/etc/php5/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 128M|" $PHPINI
sed -i "s|^upload_max_filesize.*|upload_max_filesize = 16M|" $PHPINI
sed -i "s|^post_max_size.*|post_max_size = 48M|" $PHPINI
sed -i "s|^allow_url_fopen.*|allow_url_fopen = On|" $PHPINI


# start mysql server
/etc/init.d/mysql start

# create the database and user
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
CREATE DATABASE $NAME;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER
ON $NAME.*
TO $NAME@localhost
IDENTIFIED BY '$DB_PASSWORD';
FLUSH PRIVILEGES;
EOF


## create opencart config file
cat > $CONFIG_FILE << EOF
<?php
// HTTP

define('HTTP_SERVER', 'http://127.0.0.1/');

// HTTPS
define('HTTPS_SERVER', 'http://127.0.0.1/');

// DIR
define('DIR_APPLICATION', '$OCROOT/catalog/');
define('DIR_SYSTEM', '$OCROOT/system/');
define('DIR_LANGUAGE', '$OCROOT/catalog/language/');
define('DIR_TEMPLATE', '$OCROOT/catalog/view/theme/');
define('DIR_CONFIG', '$OCROOT/system/config/');
define('DIR_IMAGE', '$OCROOT/image/');
define('DIR_CACHE', '$OCROOT/system/cache/');
define('DIR_DOWNLOAD', '$OCROOT/system/download/');
define('DIR_UPLOAD', '$OCROOT/system/upload/');
define('DIR_MODIFICATION', '$OCROOT/system/modification/');
define('DIR_LOGS', '$OCROOT/system/logs/');
define('IMAGE_OPTIMIZE', false);

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', '$NAME');
define('DB_PASSWORD', '$DB_PASSWORD');
define('DB_DATABASE', '$NAME');
define('DB_PREFIX', '$DB_PREFIX');
EOF

## create opencart adminconfig file
cat > $ADMINCONFIG_FILE << EOF
<?php
define('HTTP_SERVER', 'http://127.0.0.1/admin/');
define('HTTP_CATALOG', 'http://127.0.0.1/');

// HTTPS
define('HTTPS_SERVER', 'http://127.0.0.1/admin/');
define('HTTPS_CATALOG', 'http://127.0.0.1/');

// DIR
define('DIR_APPLICATION', '$OCROOT/admin/');
define('DIR_SYSTEM', '$OCROOT/system/');
define('DIR_LANGUAGE', '$OCROOT/admin/language/');
define('DIR_TEMPLATE', '$OCROOT/admin/view/template/');
define('DIR_CATALOG_TEMPLATE', '$OCROOT/catalog/view/template/');
define('DIR_CONFIG', '$OCROOT/system/config/');
define('DIR_IMAGE', '$OCROOT/image/');
define('DIR_CACHE', '$OCROOT/system/cache/');
define('DIR_DOWNLOAD', '$OCROOT/system/download/');
define('DIR_UPLOAD', '$OCROOT/system/upload/');
define('DIR_LOGS', '$OCROOT/system/logs/');
define('DIR_MODIFICATION', '$OCROOT/system/modification/');
define('DIR_CATALOG', '$OCROOT/catalog/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', '$NAME');
define('DB_PASSWORD', '$DB_PASSWORD');
define('DB_DATABASE', '$NAME');
define('DB_PREFIX', '$DB_PREFIX');
EOF
# setup apache configuration and complete  installation
a2dissite 000-default
a2ensite opencart
a2enmod rewrite


# fix permissions 

chown -R www-data:www-data $OCROOT


# stop services
/etc/init.d/mysql stop

